# Generated by Django 6.1.2 on 2026-10-08 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tansaction',
            new_name='Transaction',
        ),
    ]
